### ISSUE TITLE
Zarr-python should be pinned to >=3.0.0

### ISSUE THREAD

**Issue by MeyerBender** [scverse/spatialdata#1081]
Hi,

the recent version of `spatialdata` does not work with `zarr<3.0.0` anymore. With `zarr==2.18.7`, when I try to `import spatialdata`, I get the following:

```
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import spatialdata
  File "/g/huber/users/meyerben/notebooks/codex_analysis/2024-03-18_spatialproteomics_package/notebooks/2026-02-27_test_spatialdata_versions/.venv/lib/python3.13/site-packages/spatialdata/__init__.py", line 72, in <module>
    from spatialdata._io._utils import get_dask_backing_files
  File "/g/huber/users/meyerben/notebooks/codex_analysis/2024-03-18_spatialproteomics_package/notebooks/2026-02-27_test_spatialdata_versions/.venv/lib/python3.13/site-packages/spatialdata/_io/__init__.py", line 1, in <module>
    from spatialdata._io._utils import get_dask_backing_files
  File "/g/huber/users/meyerben/notebooks/codex_analysis/2024-03-18_spatialproteomics_package/notebooks/2026-02-27_test_spatialdata_versions/.venv/lib/python3.13/site-packages/spatialdata/_io/_utils.py", line 24, in <module>
    from zarr.storage import FsspecStore, LocalStore
ImportError: cannot import name 'FsspecStore' from 'zarr.storage' (/g/huber/users/meyerben/notebooks/codex_analysis/2024-03-18_spatialproteomics_package/notebooks/2026-02-27_test_spatialdata_versions/.venv/lib/python3.13/site-packages/zarr/storage.py)
```

The issue is that `spatialdata` is importing "FsspecStore", which was only introduced in version 3. So I think zarr should be pinned accordingly.
